// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="@nuxtjs/eslint-module" />
/// <reference types="@nuxtjs/vuetify" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
export {}
